import type { ControlTowerSnapshot } from "@/types";

/** Synthetic lab snapshot — demo only, not production monitoring. */
export const FALLBACK_TOWER: ControlTowerSnapshot = {
  generated_at: "2026-07-09T16:00:00+00:00",
  overall_reliability: 74.5,
  sources_monitored: 3,
  open_incidents: 3,
  failing_slas: 2,
  executive_summary:
    "Lab demo: Control Tower monitors 3 synthetic sources with overall reliability 74.5/100. Support freshness SLA is breached, Marketing shows schema drift (missing `leads`), and Orders remains healthy with a soft null-rate watch.",
  metadata: {
    connectors: ["csv", "api", "sheets"],
    demo_mode: true,
    lab: true,
    notice: "Synthetic demo dataset — not connected to a real warehouse.",
  },
  scorecards: [
    {
      source_id: "src_orders_daily",
      source_name: "Orders Daily Extract",
      reliability_score: 92,
      freshness_status: "ok",
      schema_status: "ok",
      volume_status: "ok",
      quality_status: "healthy",
      open_incidents: 1,
      last_run_at: "2026-07-09T14:02:00+00:00",
      sla_hours: 12,
      trend: [80, 87, 90, 92],
    },
    {
      source_id: "src_support_api",
      source_name: "Support Tickets API",
      reliability_score: 60,
      freshness_status: "breach",
      schema_status: "ok",
      volume_status: "ok",
      quality_status: "degraded",
      open_incidents: 1,
      last_run_at: "2026-07-09T08:02:00+00:00",
      sla_hours: 6,
      trend: [48, 55, 58, 60],
    },
    {
      source_id: "src_marketing_sheets",
      source_name: "Marketing Spend Sheet",
      reliability_score: 71.5,
      freshness_status: "breach",
      schema_status: "drift",
      volume_status: "ok",
      quality_status: "degraded",
      open_incidents: 1,
      last_run_at: "2026-07-08T10:02:00+00:00",
      sla_hours: 24,
      trend: [59.5, 66.5, 69.5, 71.5],
    },
  ],
  recent_runs: [
    {
      run_id: "run_orders_latest",
      source_id: "src_orders_daily",
      started_at: "2026-07-09T14:00:00+00:00",
      finished_at: "2026-07-09T14:02:00+00:00",
      status: "healthy",
      row_count: 120,
      column_count: 7,
      freshness_hours: 2,
      quality_score: 92,
      checks: [
        {
          check_id: "freshness_sla",
          name: "Freshness within SLA",
          passed: true,
          severity: "info",
          observed: 2,
          threshold: 12,
          message: "Dataset is 2.0h old against SLA of 12h.",
        },
        {
          check_id: "null_rate",
          name: "Null rate under threshold",
          passed: true,
          severity: "info",
          observed: 0.08,
          threshold: 0.15,
          message: "Overall null rate is 8.0%.",
        },
      ],
      schema_fingerprint: "a1b2c3d4e5f60718",
      volume_delta_pct: 8.7,
      duplicate_rate: 0,
      null_rate: 0.08,
    },
    {
      run_id: "run_support_latest",
      source_id: "src_support_api",
      started_at: "2026-07-09T08:00:00+00:00",
      finished_at: "2026-07-09T08:02:00+00:00",
      status: "degraded",
      row_count: 80,
      column_count: 6,
      freshness_hours: 8,
      quality_score: 60,
      checks: [
        {
          check_id: "freshness_sla",
          name: "Freshness within SLA",
          passed: false,
          severity: "critical",
          observed: 8,
          threshold: 6,
          message: "Dataset is 8.0h old against SLA of 6h.",
        },
      ],
      schema_fingerprint: "f0e1d2c3b4a59687",
      volume_delta_pct: -4.8,
      duplicate_rate: 0.012,
      null_rate: 0.03,
    },
    {
      run_id: "run_marketing_latest",
      source_id: "src_marketing_sheets",
      started_at: "2026-07-08T10:00:00+00:00",
      finished_at: "2026-07-08T10:02:00+00:00",
      status: "degraded",
      row_count: 30,
      column_count: 5,
      freshness_hours: 30,
      quality_score: 71.5,
      checks: [
        {
          check_id: "schema_columns",
          name: "Schema columns present",
          passed: false,
          severity: "critical",
          observed: "leads",
          threshold: "all expected columns",
          message: "Missing columns: ['leads']",
        },
        {
          check_id: "freshness_sla",
          name: "Freshness within SLA",
          passed: false,
          severity: "critical",
          observed: 30,
          threshold: 24,
          message: "Dataset is 30.0h old against SLA of 24h.",
        },
      ],
      schema_fingerprint: "9988776655443322",
      volume_delta_pct: 0,
      duplicate_rate: 0,
      null_rate: 0.02,
    },
  ],
  incidents: [
    {
      id: "inc_001",
      source_id: "src_support_api",
      title: "Freshness SLA breached — Support Tickets API",
      severity: "critical",
      status: "investigating",
      opened_at: "2026-07-09T09:00:00+00:00",
      summary:
        "Last successful ingest is older than the 6h SLA. Downstream CX dashboards may show stale queues.",
      recommended_action:
        "Replay connector, verify API token and pagination, then re-run quality suite.",
      related_run_id: "run_support_latest",
    },
    {
      id: "inc_002",
      source_id: "src_marketing_sheets",
      title: "Schema drift — missing expected column `leads`",
      severity: "high",
      status: "open",
      opened_at: "2026-07-08T11:00:00+00:00",
      summary:
        "Marketing sheet fingerprint changed. Contract expects `leads`; observed schema diverged in the synthetic seed.",
      recommended_action:
        "Confirm sheet header rename with Growth owner and update data contract.",
      related_run_id: "run_marketing_latest",
    },
    {
      id: "inc_003",
      source_id: "src_orders_daily",
      title: "Elevated null rate on shipping_city",
      severity: "medium",
      status: "mitigated",
      opened_at: "2026-07-07T16:00:00+00:00",
      summary:
        "Null rate crossed soft threshold on a non-critical dimension. Score still healthy.",
      recommended_action:
        "Backfill city from ZIP when available; keep monitoring for 3 runs.",
      related_run_id: "run_orders_latest",
    },
  ],
};
